# Generated by Django 2.2.6 on 2019-11-11 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20191110_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['first_name']},
        ),
    ]
