# Generated by Django 2.2.6 on 2019-11-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20191110_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
