# Generated by Django 2.2.6 on 2019-11-08 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=45, verbose_name='Photo Description')),
                ('instagram_link', models.URLField(blank=True, default='', max_length=300, verbose_name='Instagram Link')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='', upload_to='gallery_images', verbose_name='Image File')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_src', models.CharField(max_length=300)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Photo')),
                ('video_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Video')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
    ]
